name: "Chromatic"
on: push

jobs:
  chromatic-deployment:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: npm ci
    - uses: chromaui/action@v1
      with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          autoAcceptChanges: ${{ github.ref == 'refs/heads/master' }}
          exitOnceUploaded: true
